# -*- coding: utf-8 -*-
"""predictionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roEsyghCob73s7a3YbCol-4IECGOgbhq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score
from matplotlib.pyplot import rcParams

import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv("Iris.csv")
data.head()

data.tail()

data.info()

data.describe()

data.isnull().sum()

data.shape

data.columns

"""##Visualization of data

"""

sns.pairplot(data, hue = 'Species')

"""### Lets check for correlation more clearly"""

sns.heatmap(data.corr(), annot= True)

data.corr()

x=data.iloc[:, :-1]
y=data['Species']
data.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

"""#####lets build decision tree"""

classifier = DecisionTreeClassifier(criterion='entropy')

classifier.fit(X_train, y_train)

y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)

# let us print the accuracy score for the tree model
print("The accuracy score for the built model is:",accuracy_score(y_test, y_pred_test))

##Tree
rcParams['figure.figsize'] = 40, 20
plot_tree(classifier, precision=5, rounded = False, filled = True)

